#!/usr/bin/env bash
set -euo pipefail

# Run from the server/container repo:
#   cd /myapp/sglang-omni
#   TRACE_CACHE=0 FORCE_RESTART=1 \
#     bash reports/run_sglang_qwen35_stable_server.sh
# See reports/README_qwen35_realtime_benchmark_20260701.md for the C1/C12
# benchmark commands and reference numbers.
# The script intentionally leaves QWEN35_MAMBA_MEDIA_BRANCH_CACHE unset by
# default. Qwen3.5 RTC requests with omitted cached visual payloads auto-disable
# that Mamba branch cache path because it can produce unstable text/audio under
# vLLM-style interleaved prefix/actual concurrency. Set the env var explicitly
# to force a value for debugging.
# Measured RTC actual requests keep Mamba tracking enabled so the final
# chunk updates the request-local SSM state used by decode. They still skip
# writing that actual state back into the radix cache. Prefix requests populate
# the reusable cache for the next realtime chunk.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${REPO:-$(cd "$SCRIPT_DIR/.." && pwd)}"
PYTHON_BIN="${PYTHON_BIN:-}"
if [ -z "$PYTHON_BIN" ]; then
  if command -v python >/dev/null 2>&1; then
    PYTHON_BIN=python
  else
    PYTHON_BIN=python3
  fi
fi
PORT="${PORT:-8162}"
CUDA_VISIBLE_DEVICES_VALUE="${SGLANG_OMNI_CUDA_VISIBLE_DEVICES:-${CUDA_VISIBLE_DEVICES:-3,4,5}}"
FORCE_RESTART="${FORCE_RESTART:-0}"
CLEAN_ORPHAN_STAGE_WORKERS="${SGLANG_OMNI_CLEAN_ORPHAN_STAGE_WORKERS:-1}"
TRACE_CACHE="${TRACE_CACHE:-0}"
TRACE_CACHE_DETAIL="${TRACE_CACHE_DETAIL:-0}"
TRACE_CACHE_SCOPE="${TRACE_CACHE_SCOPE:-actual}"
PREFIX_CACHING_VALUE="${SGLANG_OMNI_PREFIX_CACHING:-on}"
FAST_VIDEO_PROCESSOR_VALUE="${SGLANG_OMNI_FAST_VIDEO_PROCESSOR:-1}"
FAST_VIDEO_PROCESSOR_DEVICE_VALUE="${SGLANG_OMNI_FAST_VIDEO_PROCESSOR_DEVICE:-cuda:0}"
VIDEO_PREPROCESS_CACHE_MAX_BYTES_VALUE="${SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_BYTES:-17179869184}"
VIDEO_PREPROCESS_CACHE_MAX_ENTRIES_VALUE="${SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_ENTRIES:-1024}"
OMIT_CACHED_VISUAL_ITEM_PAYLOADS_VALUE="${SGLANG_OMNI_OMIT_CACHED_VISUAL_ITEM_PAYLOADS:-1}"
PROCESSOR_ITEM_CACHE_MAX_ENTRIES_VALUE="${SGLANG_OMNI_PROCESSOR_ITEM_CACHE_MAX_ENTRIES:-2048}"
OMIT_CACHED_AUDIO_ITEM_PAYLOADS_VALUE="${SGLANG_OMNI_OMIT_CACHED_AUDIO_ITEM_PAYLOADS:-1}"
RTC_MEDIA_PREFIX_CACHE_VALUE="${SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE:-1}"
RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES_VALUE="${SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES:-64}"
MAMBA_MEDIA_BRANCH_CACHE="${QWEN35_MAMBA_MEDIA_BRANCH_CACHE:-}"
RTC_DISABLE_ACTUAL_MAMBA_TRACK="${QWEN35_RTC_DISABLE_ACTUAL_MAMBA_TRACK:-0}"
RTC_PRERUN_PREFILL_ONLY_VALUE="${QWEN35_RTC_PRERUN_PREFILL_ONLY:-1}"
RTC_SKIP_ACTUAL_MAMBA_CACHE_INSERT="${SGLANG_OMNI_SKIP_RTC_ACTUAL_MAMBA_CACHE_INSERT:-1}"
RTC_LIMIT_ACTUAL_PREFIX_TO_COMPLETE_TURN="${QWEN35_RTC_LIMIT_ACTUAL_PREFIX_TO_COMPLETE_TURN:-1}"
IMAGE_ENCODER_BATCH_BUDGET_BYTES="${SGLANG_OMNI_IMAGE_ENCODER_BATCH_BUDGET_BYTES:-2147483648}"
IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES_VALUE="${SGLANG_OMNI_IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES:-2147483648}"
IMAGE_ENCODER_TORCH_COMPILE_VALUE="${SGLANG_OMNI_IMAGE_ENCODER_TORCH_COMPILE:-1}"
ENCODER_MAX_BATCH_WAIT_MS_VALUE="${SGLANG_OMNI_ENCODER_MAX_BATCH_WAIT_MS:-50}"
RELAY_SLOT_SIZE_MB_VALUE="${SGLANG_OMNI_RELAY_SLOT_SIZE_MB:-1024}"
RELAY_CREDITS_VALUE="${SGLANG_OMNI_RELAY_CREDITS:-2}"
AR_BUSY_YIELD_SECONDS_VALUE="${SGLANG_OMNI_AR_BUSY_YIELD_SECONDS:-0.001}"
CODE2WAV_STREAM_INGEST_YIELD_EVERY_MESSAGES_VALUE="${SGLANG_OMNI_STREAM_INGEST_YIELD_EVERY_MESSAGES_CODE2WAV:-8}"
CODE2WAV_STAGE_IO_YIELD_EVERY_MESSAGES_VALUE="${SGLANG_OMNI_STAGE_IO_YIELD_EVERY_MESSAGES_CODE2WAV:-}"
PRIORITY_PREFILL_MAX_BATCH_SIZE_VALUE="${SGLANG_OMNI_PRIORITY_PREFILL_MAX_BATCH_SIZE:-12}"
PRIORITY_PREFILL_MAX_TOKENS_VALUE="${SGLANG_OMNI_PRIORITY_PREFILL_MAX_TOKENS:-0}"
PRIORITY_DECODE_WARMUP_CHUNKS_VALUE="${SGLANG_OMNI_PRIORITY_DECODE_WARMUP_CHUNKS:-4}"
DECODE_STREAM_TOKEN_BATCH_SIZE_VALUE="${SGLANG_OMNI_DECODE_STREAM_TOKEN_BATCH_SIZE:-8}"
TALKER_READY_SUBSET_MIN_SIZE_VALUE="${SGLANG_OMNI_TALKER_READY_SUBSET_MIN_SIZE:-1}"
TALKER_PARTIAL_START_MIN_CHUNKS_VALUE="${SGLANG_OMNI_TALKER_PARTIAL_START_MIN_CHUNKS:-4}"
CODE2WAV_STREAM_CHUNK_SIZE_VALUE="${SGLANG_OMNI_CODE2WAV_STREAM_CHUNK_SIZE:-4}"
CODE2WAV_DYNAMIC_CHUNK_VALUE="${SGLANG_OMNI_CODE2WAV_DYNAMIC_CHUNK:-off}"
CODE2WAV_DYNAMIC_CHUNK_SIZES_VALUE="${SGLANG_OMNI_CODE2WAV_DYNAMIC_CHUNK_SIZES:-}"
CODE2WAV_DYNAMIC_CHUNK_STEPS_VALUE="${SGLANG_OMNI_CODE2WAV_DYNAMIC_CHUNK_STEPS:-}"
SUBTALKER_TORCH_COMPILE_VALUE="${SGLANG_OMNI_QWEN35_SUBTALKER_TORCH_COMPILE:-1}"
TALKER_CODEC_STREAM_INLINE_CPU_VALUE="${SGLANG_OMNI_TALKER_CODEC_STREAM_INLINE_CPU:-1}"
TALKER_CODEC_STREAM_GROUP_SIZE_VALUE="${SGLANG_OMNI_TALKER_CODEC_STREAM_GROUP_SIZE:-1}"
TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE_VALUE="${QWEN35_TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE:-0}"
TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS_VALUE="${QWEN35_TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS:-0}"
TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK_VALUE="${QWEN35_TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK:-0}"
DEFER_PREFILL_DURING_PRIORITY_DECODE_VALUE="${SGLANG_OMNI_DEFER_PREFILL_DURING_PRIORITY_DECODE:-1}"
ISOLATED_PREFILL_MAX_BATCH_SIZE_VALUE="${SGLANG_OMNI_ISOLATED_PREFILL_MAX_BATCH_SIZE:-12}"
PREPROCESSING_MAX_CONCURRENCY_VALUE="${PREPROCESSING_MAX_CONCURRENCY:-2}"
ENCODER_CACHE_DEVICE_VALUE="${SGLANG_OMNI_ENCODER_CACHE_DEVICE:-cuda}"
ENCODER_CACHE_CLONE_ON_GET_VALUE="${SGLANG_OMNI_ENCODER_CACHE_CLONE_ON_GET:-0}"
IMAGE_ENCODER_GPU_VALUE="${SGLANG_OMNI_IMAGE_ENCODER_GPU:-}"
IMAGE_ENCODER_GPUS_VALUE="${SGLANG_OMNI_IMAGE_ENCODER_GPUS:-}"
AUDIO_ENCODER_GPU_VALUE="${SGLANG_OMNI_AUDIO_ENCODER_GPU:-}"
if [ -n "${SGLANG_OMNI_FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE:-}" ]; then
  FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE_VALUE="$SGLANG_OMNI_FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE"
elif [ "$IMAGE_ENCODER_GPU_VALUE" = "0" ] && [ -z "$IMAGE_ENCODER_GPUS_VALUE" ]; then
  FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE_VALUE=device
else
  FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE_VALUE=cpu
fi
if [ -n "${SGLANG_OMNI_CACHED_VIDEO_PIXEL_FALLBACKS:-}" ]; then
  CACHED_VIDEO_PIXEL_FALLBACKS_VALUE="$SGLANG_OMNI_CACHED_VIDEO_PIXEL_FALLBACKS"
elif [ "$OMIT_CACHED_VISUAL_ITEM_PAYLOADS_VALUE" != "0" ]; then
  # Keep a recompute fallback for omitted cached video pixels. Under C12 RTC
  # pressure, an encoder item cache miss must be recoverable instead of letting
  # talker see unresolved negative media-cache placeholder ids.
  CACHED_VIDEO_PIXEL_FALLBACKS_VALUE=1
else
  CACHED_VIDEO_PIXEL_FALLBACKS_VALUE=0
fi
PROCESSOR_CACHE_CLONE_ON_SET_VALUE="${SGLANG_OMNI_PROCESSOR_CACHE_CLONE_ON_SET:-0}"
COLOCATE_PREPROCESSING_WITH_THINKER_VALUE="${SGLANG_OMNI_COLOCATE_PREPROCESSING_WITH_THINKER:-1}"
COLOCATE_IMAGE_ENCODER_WITH_THINKER_VALUE="${SGLANG_OMNI_COLOCATE_IMAGE_ENCODER_WITH_THINKER:-1}"
COLOCATE_MM_AGGREGATE_WITH_THINKER_VALUE="${SGLANG_OMNI_COLOCATE_MM_AGGREGATE_WITH_THINKER:-1}"
VISUAL_ITEM_BATCH_STATS_VALUE="${SGLANG_OMNI_VISUAL_ITEM_BATCH_STATS:-0}"
SERVER_WARMUP="${SGLANG_OMNI_SERVER_WARMUP:-1}"
THINKER_CUDA_GRAPH_VALUE="${SGLANG_OMNI_THINKER_CUDA_GRAPH:-on}"
TALKER_CUDA_GRAPH_VALUE="${SGLANG_OMNI_TALKER_CUDA_GRAPH:-on}"
THINKER_QUANTIZATION_VALUE="${SGLANG_OMNI_THINKER_QUANTIZATION:-${THINKER_QUANTIZATION:-}}"
SERVER_WARMUP_TRUNK_SIZE="${SGLANG_OMNI_SERVER_WARMUP_TRUNK_SIZE:-3}"
SERVER_WARMUP_MAX_TOKENS="${SGLANG_OMNI_SERVER_WARMUP_MAX_TOKENS:-32}"
VOICE_TYPE_VALUE="${SGLANG_OMNI_VOICE_TYPE:-${VOICE:-f245}}"
THINKER_ONLY="${SGLANG_OMNI_THINKER_ONLY:-0}"
case "$THINKER_ONLY" in
  1|true|TRUE|yes|YES)
    DEFAULT_THINKER_MAX_SEQ_LEN=192000
    DEFAULT_THINKER_MEM_FRACTION_STATIC=0.70
    DEFAULT_ENCODER_CACHE_MAX_BYTES=8589934592
    DEFAULT_SERVER_WARMUP_AUDIO_ONLY=0
    # Thinker-only RTC C12 needs enough Mamba slots for the 12 growing
    # sessions, while still leaving enough KV capacity for the final chunk.
    DEFAULT_MAX_PREFILL_TOKENS=4096
    DEFAULT_THINKER_MAX_MAMBA_CACHE_SIZE=192
    ;;
  0|false|FALSE|no|NO)
    DEFAULT_THINKER_MAX_SEQ_LEN=192000
    DEFAULT_THINKER_MEM_FRACTION_STATIC=0.70
    # Full-chain keeps a smaller GPU encoder cache on the thinker GPU so
    # long C12 benchmark sequences leave room for relay packing and CUDA graphs.
    DEFAULT_ENCODER_CACHE_MAX_BYTES=2147483648
    DEFAULT_SERVER_WARMUP_AUDIO_ONLY=0
    DEFAULT_MAX_PREFILL_TOKENS=8192
    DEFAULT_THINKER_MAX_MAMBA_CACHE_SIZE=
    ;;
  *)
    echo "SGLANG_OMNI_THINKER_ONLY must be 1/0, true/false, or yes/no; got: $THINKER_ONLY" >&2
    exit 1
    ;;
esac
SERVER_WARMUP_AUDIO_ONLY="${SGLANG_OMNI_SERVER_WARMUP_AUDIO_ONLY:-$DEFAULT_SERVER_WARMUP_AUDIO_ONLY}"
ENCODER_CACHE_MAX_BYTES_VALUE="${SGLANG_OMNI_ENCODER_CACHE_MAX_BYTES:-$DEFAULT_ENCODER_CACHE_MAX_BYTES}"
ENCODER_CACHE_MAX_ENTRIES_VALUE="${SGLANG_OMNI_ENCODER_CACHE_MAX_ENTRIES:-4096}"
THINKER_MAX_SEQ_LEN_VALUE="${SGLANG_OMNI_THINKER_MAX_SEQ_LEN:-${THINKER_MAX_SEQ_LEN:-$DEFAULT_THINKER_MAX_SEQ_LEN}}"
THINKER_MEM_FRACTION_STATIC_VALUE="${SGLANG_OMNI_THINKER_MEM_FRACTION_STATIC:-${THINKER_MEM_FRACTION_STATIC:-$DEFAULT_THINKER_MEM_FRACTION_STATIC}}"
THINKER_MAX_RUNNING_REQUESTS_VALUE="${SGLANG_OMNI_THINKER_MAX_RUNNING_REQUESTS:-${THINKER_MAX_RUNNING_REQUESTS:-12}}"
TALKER_MAX_RUNNING_REQUESTS_VALUE="${SGLANG_OMNI_TALKER_MAX_RUNNING_REQUESTS:-${TALKER_MAX_RUNNING_REQUESTS:-12}}"
MAX_PREFILL_TOKENS_VALUE="${SGLANG_OMNI_MAX_PREFILL_TOKENS:-${MAX_PREFILL_TOKENS:-$DEFAULT_MAX_PREFILL_TOKENS}}"
CHUNKED_PREFILL_SIZE_VALUE="${SGLANG_OMNI_CHUNKED_PREFILL_SIZE:-${CHUNKED_PREFILL_SIZE:-}}"
MAX_MAMBA_CACHE_SIZE_VALUE="${SGLANG_OMNI_MAX_MAMBA_CACHE_SIZE:-${MAX_MAMBA_CACHE_SIZE:-}}"
THINKER_MAX_MAMBA_CACHE_SIZE_VALUE="${SGLANG_OMNI_THINKER_MAX_MAMBA_CACHE_SIZE:-${THINKER_MAX_MAMBA_CACHE_SIZE:-$DEFAULT_THINKER_MAX_MAMBA_CACHE_SIZE}}"
MAMBA_SCHEDULER_STRATEGY_VALUE="${SGLANG_OMNI_MAMBA_SCHEDULER_STRATEGY:-}"
MULTI_CHUNKED_PREFILL_VALUE="${SGLANG_OMNI_MULTI_CHUNKED_PREFILL:-}"
MULTI_CHUNKED_PREFILL_CHUNK_SIZE_VALUE="${SGLANG_OMNI_MULTI_CHUNKED_PREFILL_CHUNK_SIZE:-}"
MULTI_CHUNKED_PREFILL_MIN_EXTEND_LEN_VALUE="${SGLANG_OMNI_MULTI_CHUNKED_PREFILL_MIN_EXTEND_LEN:-}"
MULTI_CHUNKED_PREFILL_BATCH_TOKENS_VALUE="${SGLANG_OMNI_MULTI_CHUNKED_PREFILL_BATCH_TOKENS:-}"
MULTI_CHUNKED_PREFILL_LONG_EXTEND_LEN_VALUE="${SGLANG_OMNI_MULTI_CHUNKED_PREFILL_LONG_EXTEND_LEN:-}"
MULTI_CHUNKED_PREFILL_LONG_CHUNK_SIZE_VALUE="${SGLANG_OMNI_MULTI_CHUNKED_PREFILL_LONG_CHUNK_SIZE:-}"

cd "$REPO"

MODEL_PATH="/myapp/models/qwen3_5_omni_23b_final_multilingual_all_voice_bf16_0315"
CODE2WAV_PATH="$MODEL_PATH/qwen3_5_omni_codec_decode_online_0306"

collect_stable_stop_pids() {
  "$PYTHON_BIN" - "$PORT" "$CLEAN_ORPHAN_STAGE_WORKERS" <<'PY'
import os
import sys
from collections import defaultdict

port = int(sys.argv[1])
clean_orphans = sys.argv[2].lower() in {"1", "true", "yes", "y", "on"}


def read_cmdline(pid: int) -> str:
    try:
        raw = open(f"/proc/{pid}/cmdline", "rb").read()
    except OSError:
        return ""
    if not raw:
        try:
            return open(f"/proc/{pid}/comm", "r", encoding="utf-8").read().strip()
        except OSError:
            return ""
    return raw.replace(b"\x00", b" ").decode("utf-8", errors="replace").strip()


def read_ppid(pid: int) -> int:
    try:
        fields = open(f"/proc/{pid}/stat", "r", encoding="utf-8").read().split()
        return int(fields[3])
    except Exception:
        return 0


def listener_inodes(port: int) -> set[str]:
    wanted = f"{port:04X}"
    found: set[str] = set()
    for table in ("/proc/net/tcp", "/proc/net/tcp6"):
        try:
            rows = open(table, "r", encoding="utf-8").read().splitlines()[1:]
        except OSError:
            continue
        for row in rows:
            parts = row.split()
            if len(parts) < 10 or parts[3] != "0A":
                continue
            local = parts[1]
            if ":" not in local:
                continue
            _, hex_port = local.rsplit(":", 1)
            if hex_port.upper() == wanted:
                found.add(parts[9])
    return found


procs: dict[int, tuple[int, str]] = {}
children: dict[int, list[int]] = defaultdict(list)
for name in os.listdir("/proc"):
    if not name.isdigit():
        continue
    pid = int(name)
    ppid = read_ppid(pid)
    cmd = read_cmdline(pid)
    procs[pid] = (ppid, cmd)
    children[ppid].append(pid)

roots: set[int] = set()
port_forms = {f"--port {port}", f"--port={port}"}
for pid, (_, cmd) in procs.items():
    if "sglang_omni.cli" in cmd and "serve" in cmd and any(form in cmd for form in port_forms):
        roots.add(pid)

inodes = listener_inodes(port)
if inodes:
    for name in os.listdir("/proc"):
        if not name.isdigit():
            continue
        pid = int(name)
        fd_dir = f"/proc/{pid}/fd"
        try:
            fds = os.listdir(fd_dir)
        except OSError:
            continue
        for fd in fds:
            try:
                target = os.readlink(f"{fd_dir}/{fd}")
            except OSError:
                continue
            if target.startswith("socket:[") and target[8:-1] in inodes:
                roots.add(pid)
                break

to_stop = set(roots)
stack = list(roots)
while stack:
    pid = stack.pop()
    for child in children.get(pid, []):
        if child not in to_stop:
            to_stop.add(child)
            stack.append(child)

if clean_orphans:
    for pid, (ppid, cmd) in procs.items():
        if ppid != 1:
            continue
        if (
            "from multiprocessing.spawn import spawn_main" in cmd
            or "from multiprocessing.resource_tracker import main" in cmd
        ):
            to_stop.add(pid)

current = {os.getpid(), os.getppid()}
print(" ".join(str(pid) for pid in sorted(to_stop - current, reverse=True)))
PY
}

existing_pid="$(ps -eo pid,args | awk -v port="$PORT" '/sglang_omni.cli serve/ && index($0, "--port " port) && !/awk/ {print $1; exit}')"
if [ -n "$existing_pid" ] && [ "$FORCE_RESTART" != "1" ]; then
  echo "Stable server is already running on port $PORT: pid=$existing_pid"
  curl -fsS "http://127.0.0.1:$PORT/v1/models" >/tmp/qwen35_stable_models.json
  cat /tmp/qwen35_stable_models.json
  echo
  exit 0
fi

if [ "$FORCE_RESTART" = "1" ]; then
  stop_pids="$(collect_stable_stop_pids || true)"
  if [ -n "$stop_pids" ]; then
    echo "Stopping stable server process group on port $PORT: $stop_pids"
    kill $stop_pids || true
  fi
  for _ in $(seq 1 30); do
    remaining="$(collect_stable_stop_pids || true)"
    if [ -z "$remaining" ]; then
      break
    fi
    sleep 1
  done
  remaining="$(collect_stable_stop_pids || true)"
  if [ -n "$remaining" ]; then
    echo "Force stopping existing stable server process tree on port $PORT: $remaining"
    kill -9 $remaining || true
  fi
fi

"$PYTHON_BIN" - "$PORT" <<'PY'
import socket
import sys
import time

port = int(sys.argv[1])
for _ in range(30):
    sock = socket.socket()
    sock.settimeout(0.5)
    try:
        sock.connect(("127.0.0.1", port))
    except OSError:
        sock.close()
        break
    sock.close()
    time.sleep(1)
else:
    raise SystemExit(f"port {port} is still busy")
PY

RUN_DIR="results/sg_realtime_stablefast_mem072_videocache17g_cache4096_trimpartial_cg_on_run12_c2w4_relay1024_cvd345_${PORT}_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$RUN_DIR"
cat > "$RUN_DIR/config.env" <<EOF
CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES_VALUE}
SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
TORCHDYNAMO_DISABLE=0
SGLANG_OMNI_FAST_VIDEO_PROCESSOR=${FAST_VIDEO_PROCESSOR_VALUE}
SGLANG_OMNI_FAST_VIDEO_PROCESSOR_DEVICE=${FAST_VIDEO_PROCESSOR_DEVICE_VALUE}
SGLANG_OMNI_FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE=${FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE_VALUE}
SGLANG_OMNI_IMAGE_ENCODER_TORCH_COMPILE=${IMAGE_ENCODER_TORCH_COMPILE_VALUE}
SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_BYTES=${VIDEO_PREPROCESS_CACHE_MAX_BYTES_VALUE}
SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_ENTRIES=${VIDEO_PREPROCESS_CACHE_MAX_ENTRIES_VALUE}
SGLANG_OMNI_MEDIA_IN_MEMORY_HASH=0
SGLANG_OMNI_QWEN35_RTC_PROMPT_STYLE=1
SGLANG_OMNI_RELAY_PAYLOAD_PREP_EXECUTOR=1
SGLANG_OMNI_PRIORITIZE_FRONT_STAGE_STREAM_PREFILL=1
SGLANG_OMNI_COLOCATE_PREPROCESSING_WITH_THINKER=${COLOCATE_PREPROCESSING_WITH_THINKER_VALUE}
SGLANG_OMNI_COLOCATE_IMAGE_ENCODER_WITH_THINKER=${COLOCATE_IMAGE_ENCODER_WITH_THINKER_VALUE}
SGLANG_OMNI_COLOCATE_MM_AGGREGATE_WITH_THINKER=${COLOCATE_MM_AGGREGATE_WITH_THINKER_VALUE}
SGLANG_OMNI_ENCODER_MAX_BATCH_WAIT_MS=${ENCODER_MAX_BATCH_WAIT_MS_VALUE}
SGLANG_OMNI_DECODE_STREAM_TOKEN_BATCH_SIZE=${DECODE_STREAM_TOKEN_BATCH_SIZE_VALUE}
SGLANG_OMNI_TALKER_READY_SUBSET_MIN_SIZE=${TALKER_READY_SUBSET_MIN_SIZE_VALUE}
SGLANG_OMNI_TALKER_PARTIAL_START_MIN_CHUNKS=${TALKER_PARTIAL_START_MIN_CHUNKS_VALUE}
SGLANG_OMNI_CODE2WAV_STREAM_CHUNK_SIZE=${CODE2WAV_STREAM_CHUNK_SIZE_VALUE}
SGLANG_OMNI_CODE2WAV_DYNAMIC_CHUNK=${CODE2WAV_DYNAMIC_CHUNK_VALUE}
SGLANG_OMNI_CODE2WAV_DYNAMIC_CHUNK_SIZES=${CODE2WAV_DYNAMIC_CHUNK_SIZES_VALUE:-<default>}
SGLANG_OMNI_CODE2WAV_DYNAMIC_CHUNK_STEPS=${CODE2WAV_DYNAMIC_CHUNK_STEPS_VALUE:-<default>}
SGLANG_OMNI_DEFER_PREFILL_DURING_PRIORITY_DECODE=${DEFER_PREFILL_DURING_PRIORITY_DECODE_VALUE}
SGLANG_OMNI_PRIORITY_PREFILL_MAX_TOKENS=${PRIORITY_PREFILL_MAX_TOKENS_VALUE}
SGLANG_OMNI_RELAY_SLOT_SIZE_MB=${RELAY_SLOT_SIZE_MB_VALUE}
SGLANG_OMNI_RELAY_CREDITS=${RELAY_CREDITS_VALUE}
SGLANG_OMNI_IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES=${IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES_VALUE}
SGLANG_OMNI_VISUAL_ITEM_BATCH_STATS=${VISUAL_ITEM_BATCH_STATS_VALUE}
SGLANG_OMNI_ENCODER_CACHE_MAX_ENTRIES=${ENCODER_CACHE_MAX_ENTRIES_VALUE}
SGLANG_OMNI_PRIORITY_DECODE_WARMUP_CHUNKS=${PRIORITY_DECODE_WARMUP_CHUNKS_VALUE}
SGLANG_OMNI_STORE_ITEM_PLAN_COMBINED_ENCODER_CACHE=0
SGLANG_OMNI_OMIT_CACHED_VISUAL_ITEM_PAYLOADS=${OMIT_CACHED_VISUAL_ITEM_PAYLOADS_VALUE}
SGLANG_OMNI_OMIT_CACHED_AUDIO_ITEM_PAYLOADS=${OMIT_CACHED_AUDIO_ITEM_PAYLOADS_VALUE}
SGLANG_OMNI_CACHED_VIDEO_PIXEL_FALLBACKS=${CACHED_VIDEO_PIXEL_FALLBACKS_VALUE}
SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE=${RTC_MEDIA_PREFIX_CACHE_VALUE}
SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES=${RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES_VALUE}
SGLANG_OMNI_MM_AGGREGATE_RELAY_ON_THINKER_GPU=1
QWEN35_LIMIT_PREFIX_CACHE_BEFORE_MEDIA=0
QWEN35_RTC_PRERUN_PREFILL_ONLY=${RTC_PRERUN_PREFILL_ONLY_VALUE}
QWEN35_RTC_ISOLATE_PRERUN_PREFILL=1
QWEN35_RTC_LIMIT_ACTUAL_PREFIX_TO_COMPLETE_TURN=${RTC_LIMIT_ACTUAL_PREFIX_TO_COMPLETE_TURN}
SGLANG_OMNI_SKIP_NAN_MAMBA_CACHE=1
SGLANG_OMNI_SKIP_RTC_ACTUAL_MAMBA_CACHE_INSERT=1
QWEN35_TRIM_PARTIAL_TRAILING_VISUAL_FEATURES=1
QWEN35_TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE=${TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE_VALUE}
QWEN35_TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS=${TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS_VALUE}
QWEN35_TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK=${TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK_VALUE}
thinker_mem_fraction_static=${THINKER_MEM_FRACTION_STATIC_VALUE}
thinker_max_running_requests=${THINKER_MAX_RUNNING_REQUESTS_VALUE}
talker_max_running_requests=${TALKER_MAX_RUNNING_REQUESTS_VALUE}
code2wav_stream_chunk_size=${CODE2WAV_STREAM_CHUNK_SIZE_VALUE}
code2wav_dynamic_chunk=${CODE2WAV_DYNAMIC_CHUNK_VALUE}
talker_partial_start_min_chunks=4
thinker_cuda_graph=${THINKER_CUDA_GRAPH_VALUE}
talker_cuda_graph=${TALKER_CUDA_GRAPH_VALUE}
talker_torch_compile=on
EOF
printf 'SGLANG_OMNI_PREFIX_CACHING=%s\n' "$PREFIX_CACHING_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_IMAGE_ENCODER_BATCH_BUDGET_BYTES=%s\n' "$IMAGE_ENCODER_BATCH_BUDGET_BYTES" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES=%s\n' "$IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_VISUAL_ITEM_BATCH_STATS=%s\n' "$VISUAL_ITEM_BATCH_STATS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_ENCODER_MAX_BATCH_WAIT_MS=%s\n' "$ENCODER_MAX_BATCH_WAIT_MS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_AR_BUSY_YIELD_SECONDS=%s\n' "$AR_BUSY_YIELD_SECONDS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_STREAM_INGEST_YIELD_EVERY_MESSAGES_CODE2WAV=%s\n' "$CODE2WAV_STREAM_INGEST_YIELD_EVERY_MESSAGES_VALUE" >> "$RUN_DIR/config.env"
if [ -n "$CODE2WAV_STAGE_IO_YIELD_EVERY_MESSAGES_VALUE" ]; then
  printf 'SGLANG_OMNI_STAGE_IO_YIELD_EVERY_MESSAGES_CODE2WAV=%s\n' "$CODE2WAV_STAGE_IO_YIELD_EVERY_MESSAGES_VALUE" >> "$RUN_DIR/config.env"
else
  printf 'SGLANG_OMNI_STAGE_IO_YIELD_EVERY_MESSAGES_CODE2WAV=<default>\n' >> "$RUN_DIR/config.env"
fi
printf 'SGLANG_OMNI_PRIORITY_PREFILL_MAX_BATCH_SIZE=%s\n' "$PRIORITY_PREFILL_MAX_BATCH_SIZE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_PRIORITY_PREFILL_MAX_TOKENS=%s\n' "$PRIORITY_PREFILL_MAX_TOKENS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_ISOLATED_PREFILL_MAX_BATCH_SIZE=%s\n' "$ISOLATED_PREFILL_MAX_BATCH_SIZE_VALUE" >> "$RUN_DIR/config.env"
printf 'PREPROCESSING_MAX_CONCURRENCY=%s\n' "$PREPROCESSING_MAX_CONCURRENCY_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_ENCODER_CACHE_MAX_BYTES=%s\n' "$ENCODER_CACHE_MAX_BYTES_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_ENCODER_CACHE_MAX_ENTRIES=%s\n' "$ENCODER_CACHE_MAX_ENTRIES_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_ENCODER_CACHE_DEVICE=%s\n' "$ENCODER_CACHE_DEVICE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_ENCODER_CACHE_CLONE_ON_GET=%s\n' "$ENCODER_CACHE_CLONE_ON_GET_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_ENTRIES=%s\n' "$VIDEO_PREPROCESS_CACHE_MAX_ENTRIES_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_PROCESSOR_ITEM_CACHE_MAX_ENTRIES=%s\n' "$PROCESSOR_ITEM_CACHE_MAX_ENTRIES_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_IMAGE_ENCODER_GPU=%s\n' "${IMAGE_ENCODER_GPU_VALUE:-<default>}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_OMIT_CACHED_VISUAL_ITEM_PAYLOADS=%s\n' "$OMIT_CACHED_VISUAL_ITEM_PAYLOADS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_CACHED_VIDEO_PIXEL_FALLBACKS=%s\n' "$CACHED_VIDEO_PIXEL_FALLBACKS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_IMAGE_ENCODER_GPUS=%s\n' "${IMAGE_ENCODER_GPUS_VALUE:-<default>}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_AUDIO_ENCODER_GPU=%s\n' "${AUDIO_ENCODER_GPU_VALUE:-<default>}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_PROCESSOR_CACHE_CLONE_ON_SET=%s\n' "$PROCESSOR_CACHE_CLONE_ON_SET_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE=%s\n' "$RTC_MEDIA_PREFIX_CACHE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES=%s\n' "$RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_COLOCATE_PREPROCESSING_WITH_THINKER=%s\n' "$COLOCATE_PREPROCESSING_WITH_THINKER_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_COLOCATE_IMAGE_ENCODER_WITH_THINKER=%s\n' "$COLOCATE_IMAGE_ENCODER_WITH_THINKER_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_COLOCATE_MM_AGGREGATE_WITH_THINKER=%s\n' "$COLOCATE_MM_AGGREGATE_WITH_THINKER_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_SERVER_WARMUP=%s\n' "$SERVER_WARMUP" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_SERVER_WARMUP_TRUNK_SIZE=%s\n' "$SERVER_WARMUP_TRUNK_SIZE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_SERVER_WARMUP_MAX_TOKENS=%s\n' "$SERVER_WARMUP_MAX_TOKENS" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_SERVER_WARMUP_AUDIO_ONLY=%s\n' "$SERVER_WARMUP_AUDIO_ONLY" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_THINKER_ONLY=%s\n' "$THINKER_ONLY" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_THINKER_MAX_SEQ_LEN=%s\n' "$THINKER_MAX_SEQ_LEN_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_THINKER_MEM_FRACTION_STATIC=%s\n' "$THINKER_MEM_FRACTION_STATIC_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_THINKER_MAX_RUNNING_REQUESTS=%s\n' "$THINKER_MAX_RUNNING_REQUESTS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_TALKER_MAX_RUNNING_REQUESTS=%s\n' "$TALKER_MAX_RUNNING_REQUESTS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MAX_PREFILL_TOKENS=%s\n' "${MAX_PREFILL_TOKENS_VALUE:-}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_CHUNKED_PREFILL_SIZE=%s\n' "${CHUNKED_PREFILL_SIZE_VALUE:-}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MAX_MAMBA_CACHE_SIZE=%s\n' "${MAX_MAMBA_CACHE_SIZE_VALUE:-}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_THINKER_MAX_MAMBA_CACHE_SIZE=%s\n' "${THINKER_MAX_MAMBA_CACHE_SIZE_VALUE:-}" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MULTI_CHUNKED_PREFILL=%s\n' "$MULTI_CHUNKED_PREFILL_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MULTI_CHUNKED_PREFILL_CHUNK_SIZE=%s\n' "$MULTI_CHUNKED_PREFILL_CHUNK_SIZE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MULTI_CHUNKED_PREFILL_MIN_EXTEND_LEN=%s\n' "$MULTI_CHUNKED_PREFILL_MIN_EXTEND_LEN_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MULTI_CHUNKED_PREFILL_BATCH_TOKENS=%s\n' "$MULTI_CHUNKED_PREFILL_BATCH_TOKENS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MULTI_CHUNKED_PREFILL_LONG_EXTEND_LEN=%s\n' "$MULTI_CHUNKED_PREFILL_LONG_EXTEND_LEN_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_MULTI_CHUNKED_PREFILL_LONG_CHUNK_SIZE=%s\n' "$MULTI_CHUNKED_PREFILL_LONG_CHUNK_SIZE_VALUE" >> "$RUN_DIR/config.env"
printf 'QWEN35_TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE=%s\n' "$TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE_VALUE" >> "$RUN_DIR/config.env"
printf 'QWEN35_TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS=%s\n' "$TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_QWEN35_SUBTALKER_TORCH_COMPILE=%s\n' "$SUBTALKER_TORCH_COMPILE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_TALKER_CODEC_STREAM_INLINE_CPU=%s\n' "$TALKER_CODEC_STREAM_INLINE_CPU_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_TALKER_CODEC_STREAM_GROUP_SIZE=%s\n' "$TALKER_CODEC_STREAM_GROUP_SIZE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_THINKER_QUANTIZATION=%s\n' "$THINKER_QUANTIZATION_VALUE" >> "$RUN_DIR/config.env"
printf 'QWEN35_TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK=%s\n' "$TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK_VALUE" >> "$RUN_DIR/config.env"
if [ -n "$MAMBA_MEDIA_BRANCH_CACHE" ]; then
  printf 'QWEN35_MAMBA_MEDIA_BRANCH_CACHE=%s\n' "$MAMBA_MEDIA_BRANCH_CACHE" >> "$RUN_DIR/config.env"
else
  printf 'QWEN35_MAMBA_MEDIA_BRANCH_CACHE=<auto>\n' >> "$RUN_DIR/config.env"
fi
printf 'QWEN35_RTC_DISABLE_ACTUAL_MAMBA_TRACK=%s\n' "$RTC_DISABLE_ACTUAL_MAMBA_TRACK" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_SKIP_RTC_ACTUAL_MAMBA_CACHE_INSERT=%s\n' "$RTC_SKIP_ACTUAL_MAMBA_CACHE_INSERT" >> "$RUN_DIR/config.env"
printf 'TRACE_CACHE=%s\n' "$TRACE_CACHE" >> "$RUN_DIR/config.env"
printf 'TRACE_CACHE_DETAIL=%s\n' "$TRACE_CACHE_DETAIL" >> "$RUN_DIR/config.env"
printf 'TRACE_CACHE_SCOPE=%s\n' "$TRACE_CACHE_SCOPE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_FAST_VIDEO_PROCESSOR=%s\n' "$FAST_VIDEO_PROCESSOR_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_FAST_VIDEO_PROCESSOR_DEVICE=%s\n' "$FAST_VIDEO_PROCESSOR_DEVICE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE=%s\n' "$FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE_VALUE" >> "$RUN_DIR/config.env"
printf 'SGLANG_OMNI_IMAGE_ENCODER_TORCH_COMPILE=%s\n' "$IMAGE_ENCODER_TORCH_COMPILE_VALUE" >> "$RUN_DIR/config.env"
if [ "$TRACE_CACHE" = "1" ]; then
  cat >> "$RUN_DIR/config.env" <<EOF
SGLANG_OMNI_TRACE_VIDEO_PREPROCESS_CACHE=1
SGLANG_OMNI_TRACE_PROCESSOR_CACHE=1
SGLANG_OMNI_TRACE_ENCODER_CACHE=1
SGLANG_OMNI_TRACE_CACHE_SUMMARY_SCOPE=$TRACE_CACHE_SCOPE
EOF
  if [ "$TRACE_CACHE_DETAIL" = "1" ]; then
    cat >> "$RUN_DIR/config.env" <<'EOF'
SGLANG_OMNI_TRACE_PROCESSOR_CACHE_DETAIL=1
SGLANG_OMNI_TRACE_ENCODER_CACHE_DETAIL=1
EOF
  fi
fi

(
  export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES_VALUE}
  export SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
  export TORCHDYNAMO_DISABLE=0
  export SGLANG_OMNI_FAST_VIDEO_PROCESSOR="$FAST_VIDEO_PROCESSOR_VALUE"
  export SGLANG_OMNI_FAST_VIDEO_PROCESSOR_DEVICE="$FAST_VIDEO_PROCESSOR_DEVICE_VALUE"
  export SGLANG_OMNI_FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE="$FAST_VIDEO_PROCESSOR_OUTPUT_DEVICE_VALUE"
  export SGLANG_OMNI_IMAGE_ENCODER_TORCH_COMPILE="$IMAGE_ENCODER_TORCH_COMPILE_VALUE"
  export SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_BYTES="$VIDEO_PREPROCESS_CACHE_MAX_BYTES_VALUE"
  export SGLANG_OMNI_VIDEO_PREPROCESS_CACHE_MAX_ENTRIES=${VIDEO_PREPROCESS_CACHE_MAX_ENTRIES_VALUE}
  export SGLANG_OMNI_MEDIA_IN_MEMORY_HASH=0
  export SGLANG_OMNI_QWEN35_RTC_PROMPT_STYLE=1
  export SGLANG_OMNI_PROCESSOR_ITEM_CACHE_MAX_ENTRIES="$PROCESSOR_ITEM_CACHE_MAX_ENTRIES_VALUE"
  export SGLANG_OMNI_AR_BUSY_YIELD_SECONDS="$AR_BUSY_YIELD_SECONDS_VALUE"
  export SGLANG_OMNI_STREAM_INGEST_YIELD_EVERY_MESSAGES_CODE2WAV="$CODE2WAV_STREAM_INGEST_YIELD_EVERY_MESSAGES_VALUE"
  if [ -n "$CODE2WAV_STAGE_IO_YIELD_EVERY_MESSAGES_VALUE" ]; then
    export SGLANG_OMNI_STAGE_IO_YIELD_EVERY_MESSAGES_CODE2WAV="$CODE2WAV_STAGE_IO_YIELD_EVERY_MESSAGES_VALUE"
  else
    unset SGLANG_OMNI_STAGE_IO_YIELD_EVERY_MESSAGES_CODE2WAV
  fi
  export SGLANG_OMNI_PRIORITY_PREFILL_MAX_BATCH_SIZE="$PRIORITY_PREFILL_MAX_BATCH_SIZE_VALUE"
  export SGLANG_OMNI_PRIORITY_PREFILL_MAX_TOKENS="$PRIORITY_PREFILL_MAX_TOKENS_VALUE"
  export SGLANG_OMNI_PRIORITY_DECODE_WARMUP_CHUNKS="$PRIORITY_DECODE_WARMUP_CHUNKS_VALUE"
  export SGLANG_OMNI_DEFER_PREFILL_DURING_PRIORITY_DECODE="$DEFER_PREFILL_DURING_PRIORITY_DECODE_VALUE"
  export SGLANG_OMNI_ISOLATED_PREFILL_MAX_BATCH_SIZE="$ISOLATED_PREFILL_MAX_BATCH_SIZE_VALUE"
  if [ "$TRACE_CACHE" = "1" ]; then
    export SGLANG_OMNI_TRACE_VIDEO_PREPROCESS_CACHE=1
    export SGLANG_OMNI_TRACE_PROCESSOR_CACHE=1
    export SGLANG_OMNI_TRACE_ENCODER_CACHE=1
    export SGLANG_OMNI_TRACE_CACHE_SUMMARY_SCOPE="$TRACE_CACHE_SCOPE"
    if [ "$TRACE_CACHE_DETAIL" = "1" ]; then
      export SGLANG_OMNI_TRACE_PROCESSOR_CACHE_DETAIL=1
      export SGLANG_OMNI_TRACE_ENCODER_CACHE_DETAIL=1
    fi
  fi
  export SGLANG_OMNI_RELAY_PAYLOAD_PREP_EXECUTOR=1
  export SGLANG_OMNI_PRIORITIZE_FRONT_STAGE_STREAM_PREFILL=1
  export SGLANG_OMNI_COLOCATE_PREPROCESSING_WITH_THINKER="$COLOCATE_PREPROCESSING_WITH_THINKER_VALUE"
  export SGLANG_OMNI_COLOCATE_IMAGE_ENCODER_WITH_THINKER="$COLOCATE_IMAGE_ENCODER_WITH_THINKER_VALUE"
  export SGLANG_OMNI_COLOCATE_MM_AGGREGATE_WITH_THINKER="$COLOCATE_MM_AGGREGATE_WITH_THINKER_VALUE"
  export SGLANG_OMNI_ENCODER_MAX_BATCH_WAIT_MS=${ENCODER_MAX_BATCH_WAIT_MS_VALUE}
  export SGLANG_OMNI_DECODE_STREAM_TOKEN_BATCH_SIZE="$DECODE_STREAM_TOKEN_BATCH_SIZE_VALUE"
  export SGLANG_OMNI_TALKER_READY_SUBSET_MIN_SIZE="$TALKER_READY_SUBSET_MIN_SIZE_VALUE"
  export SGLANG_OMNI_RELAY_SLOT_SIZE_MB="$RELAY_SLOT_SIZE_MB_VALUE"
  export SGLANG_OMNI_RELAY_CREDITS="$RELAY_CREDITS_VALUE"
  export SGLANG_OMNI_IMAGE_ENCODER_BATCH_BUDGET_BYTES="$IMAGE_ENCODER_BATCH_BUDGET_BYTES"
  export PREPROCESSING_MAX_CONCURRENCY="$PREPROCESSING_MAX_CONCURRENCY_VALUE"
  export SGLANG_OMNI_IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES="$IMAGE_ENCODER_ITEM_BATCH_BUDGET_BYTES_VALUE"
  export SGLANG_OMNI_VISUAL_ITEM_BATCH_STATS="$VISUAL_ITEM_BATCH_STATS_VALUE"
  export SGLANG_OMNI_ENCODER_CACHE_MAX_ENTRIES="$ENCODER_CACHE_MAX_ENTRIES_VALUE"
  export SGLANG_OMNI_ENCODER_CACHE_MAX_BYTES="$ENCODER_CACHE_MAX_BYTES_VALUE"
  export SGLANG_OMNI_ENCODER_CACHE_DEVICE="$ENCODER_CACHE_DEVICE_VALUE"
  export SGLANG_OMNI_ENCODER_CACHE_CLONE_ON_GET="$ENCODER_CACHE_CLONE_ON_GET_VALUE"
  if [ -n "$IMAGE_ENCODER_GPU_VALUE" ]; then export SGLANG_OMNI_IMAGE_ENCODER_GPU="$IMAGE_ENCODER_GPU_VALUE"; fi
  if [ -n "$IMAGE_ENCODER_GPUS_VALUE" ]; then export SGLANG_OMNI_IMAGE_ENCODER_GPUS="$IMAGE_ENCODER_GPUS_VALUE"; fi
  export SGLANG_OMNI_OMIT_CACHED_VISUAL_ITEM_PAYLOADS="$OMIT_CACHED_VISUAL_ITEM_PAYLOADS_VALUE"
  export SGLANG_OMNI_CACHED_VIDEO_PIXEL_FALLBACKS="$CACHED_VIDEO_PIXEL_FALLBACKS_VALUE"
  if [ -n "$AUDIO_ENCODER_GPU_VALUE" ]; then export SGLANG_OMNI_AUDIO_ENCODER_GPU="$AUDIO_ENCODER_GPU_VALUE"; fi
  export SGLANG_OMNI_PROCESSOR_CACHE_CLONE_ON_SET="$PROCESSOR_CACHE_CLONE_ON_SET_VALUE"
  export SGLANG_OMNI_VOICE_TYPE="$VOICE_TYPE_VALUE"
  export SGLANG_OMNI_STORE_ITEM_PLAN_COMBINED_ENCODER_CACHE=0
  export SGLANG_OMNI_OMIT_CACHED_VISUAL_ITEM_PAYLOADS="$OMIT_CACHED_VISUAL_ITEM_PAYLOADS_VALUE"
  export SGLANG_OMNI_OMIT_CACHED_AUDIO_ITEM_PAYLOADS="$OMIT_CACHED_AUDIO_ITEM_PAYLOADS_VALUE"
  export SGLANG_OMNI_CACHED_VIDEO_PIXEL_FALLBACKS="$CACHED_VIDEO_PIXEL_FALLBACKS_VALUE"
  export SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE="$RTC_MEDIA_PREFIX_CACHE_VALUE"
  export SGLANG_OMNI_RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES="$RTC_MEDIA_PREFIX_CACHE_MAX_ENTRIES_VALUE"
  export SGLANG_OMNI_MM_AGGREGATE_RELAY_ON_THINKER_GPU=1
  export QWEN35_LIMIT_PREFIX_CACHE_BEFORE_MEDIA=0
  if [ -n "$MAMBA_MEDIA_BRANCH_CACHE" ]; then
    export QWEN35_MAMBA_MEDIA_BRANCH_CACHE="$MAMBA_MEDIA_BRANCH_CACHE"
  fi
  export QWEN35_RTC_PRERUN_PREFILL_ONLY="$RTC_PRERUN_PREFILL_ONLY_VALUE"
  export QWEN35_RTC_ISOLATE_PRERUN_PREFILL=1
  export QWEN35_RTC_LIMIT_ACTUAL_PREFIX_TO_COMPLETE_TURN="$RTC_LIMIT_ACTUAL_PREFIX_TO_COMPLETE_TURN"
  export QWEN35_RTC_DISABLE_ACTUAL_MAMBA_TRACK="$RTC_DISABLE_ACTUAL_MAMBA_TRACK"
  export SGLANG_OMNI_SKIP_NAN_MAMBA_CACHE=1
  export SGLANG_OMNI_SKIP_RTC_ACTUAL_MAMBA_CACHE_INSERT="$RTC_SKIP_ACTUAL_MAMBA_CACHE_INSERT"
  export QWEN35_TRIM_PARTIAL_TRAILING_VISUAL_FEATURES=1
  export QWEN35_TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE=${TALKER_ALLOW_PARTIAL_TEXT_CHUNK_BEFORE_DONE_VALUE}
  export QWEN35_TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS=${TALKER_PARTIAL_TEXT_CHUNK_WAIT_SKIPS_VALUE}
  export SGLANG_OMNI_QWEN35_SUBTALKER_TORCH_COMPILE="$SUBTALKER_TORCH_COMPILE_VALUE"
  export SGLANG_OMNI_TALKER_CODEC_STREAM_INLINE_CPU="$TALKER_CODEC_STREAM_INLINE_CPU_VALUE"
  export SGLANG_OMNI_TALKER_CODEC_STREAM_GROUP_SIZE="$TALKER_CODEC_STREAM_GROUP_SIZE_VALUE"
  export QWEN35_TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK=${TALKER_ALLOW_UNBOUNDED_EMPTY_TEXT_FEEDBACK_VALUE}
  export PYTHONPATH=.
  serve_args=(
    --model-path "$MODEL_PATH"
    --model-name qwen3_5-omni
    --host 127.0.0.1
    --port "$PORT"
    --max-tokens 512
    --seed 3408
    --thinker-gpus 0
    --thinker-max-seq-len "$THINKER_MAX_SEQ_LEN_VALUE"
    --prefix-caching "$PREFIX_CACHING_VALUE"
    --thinker-mem-fraction-static "$THINKER_MEM_FRACTION_STATIC_VALUE"
    --relay-backend nixl
    --thinker-cuda-graph "$THINKER_CUDA_GRAPH_VALUE"
    --thinker-max-running-requests "$THINKER_MAX_RUNNING_REQUESTS_VALUE"
  )
  if [ -n "$MAX_PREFILL_TOKENS_VALUE" ]; then
    serve_args+=(--max-prefill-tokens "$MAX_PREFILL_TOKENS_VALUE")
  fi
  if [ -n "$CHUNKED_PREFILL_SIZE_VALUE" ]; then
    serve_args+=(--chunked-prefill-size "$CHUNKED_PREFILL_SIZE_VALUE")
  fi
  if [ -n "$MAX_MAMBA_CACHE_SIZE_VALUE" ]; then
    serve_args+=(--max-mamba-cache-size "$MAX_MAMBA_CACHE_SIZE_VALUE")
  fi
  if [ -n "$THINKER_MAX_MAMBA_CACHE_SIZE_VALUE" ]; then
    serve_args+=(--thinker-max-mamba-cache-size "$THINKER_MAX_MAMBA_CACHE_SIZE_VALUE")
  fi
  if [ -n "$MAMBA_SCHEDULER_STRATEGY_VALUE" ]; then
    serve_args+=(--mamba-scheduler-strategy "$MAMBA_SCHEDULER_STRATEGY_VALUE")
  fi
  if [ -n "$THINKER_QUANTIZATION_VALUE" ]; then
    serve_args+=(--thinker-quantization "$THINKER_QUANTIZATION_VALUE")
  fi
  case "$THINKER_ONLY" in
    1|true|TRUE|yes|YES)
      serve_args+=(--text-only)
      ;;
    0|false|FALSE|no|NO)
      serve_args+=(
        --voice-type "$VOICE_TYPE_VALUE"
        --talker-gpu 1
        --code2wav-gpu 2
        --code2wav-model-path "$CODE2WAV_PATH"
        --code2wav-stream-chunk-size "$CODE2WAV_STREAM_CHUNK_SIZE_VALUE"
        --code2wav-dynamic-chunk "$CODE2WAV_DYNAMIC_CHUNK_VALUE"
        --talker-partial-start-min-chunks "$TALKER_PARTIAL_START_MIN_CHUNKS_VALUE"
        --talker-cuda-graph "$TALKER_CUDA_GRAPH_VALUE"
        --talker-torch-compile on
        --talker-max-running-requests "$TALKER_MAX_RUNNING_REQUESTS_VALUE"
      )
      if [ -n "$CODE2WAV_DYNAMIC_CHUNK_SIZES_VALUE" ]; then
        serve_args+=(--code2wav-dynamic-chunk-sizes "$CODE2WAV_DYNAMIC_CHUNK_SIZES_VALUE")
      fi
      if [ -n "$CODE2WAV_DYNAMIC_CHUNK_STEPS_VALUE" ]; then
        serve_args+=(--code2wav-dynamic-chunk-steps "$CODE2WAV_DYNAMIC_CHUNK_STEPS_VALUE")
      fi
      ;;
    *)
      echo "SGLANG_OMNI_THINKER_ONLY must be 1/0, true/false, or yes/no; got: $THINKER_ONLY" >&2
      exit 1
      ;;
  esac
  nohup "$PYTHON_BIN" -m sglang_omni.cli serve "${serve_args[@]}" \
    > "$RUN_DIR/server.log" 2>&1 &
  echo $! > "$RUN_DIR/server.pid"
)

echo "$PORT" > "$RUN_DIR/port.txt"
echo "RUN_DIR=$RUN_DIR"
echo "PID=$(cat "$RUN_DIR/server.pid")"

for i in $(seq 1 240); do
  if grep -q 'Using port .* instead' "$RUN_DIR/server.log" 2>/dev/null; then
    echo "Stable server fell back to a different port; expected $PORT" >&2
    tail -n 40 "$RUN_DIR/server.log" >&2
    exit 1
  fi
  if curl -fsS "http://127.0.0.1:$PORT/v1/models" >/tmp/qwen35_stable_models.json 2>/tmp/qwen35_stable_curl.err; then
    echo "ready_after=${i}s"
    cat /tmp/qwen35_stable_models.json
    echo
    case "$SERVER_WARMUP" in
      1|true|TRUE|yes|YES)
        warmup_text_args=()
        warmup_media_args=()
        case "$SERVER_WARMUP_AUDIO_ONLY" in
          1|true|TRUE|yes|YES)
            warmup_media_args=(--audio-only)
            warmup_media_label="audioonly"
            ;;
          0|false|FALSE|no|NO)
            warmup_media_label="av"
            ;;
          *)
            echo "SGLANG_OMNI_SERVER_WARMUP_AUDIO_ONLY must be 1/0, true/false, or yes/no; got: $SERVER_WARMUP_AUDIO_ONLY" >&2
            exit 1
            ;;
        esac
        warmup_label="$warmup_media_label"
        case "$THINKER_ONLY" in
          1|true|TRUE|yes|YES)
            warmup_text_args=(--text-only)
            warmup_label="thinkeronly_${warmup_media_label}"
            ;;
        esac
        WARMUP_DIR="$RUN_DIR/server_warmup_${warmup_label}_t${SERVER_WARMUP_TRUNK_SIZE}_$(date +%H%M%S)"
        echo "server_warmup=$warmup_label trunk=$SERVER_WARMUP_TRUNK_SIZE max_tokens=$SERVER_WARMUP_MAX_TOKENS out_dir=$WARMUP_DIR"
        PYTHONPATH=. "$PYTHON_BIN" benchmarks/eval/qwen35_omni_sglang_rtc_concurrency.py \
          --base-url "http://127.0.0.1:${PORT}" \
          --model qwen3_5-omni \
          --output-dir "$WARMUP_DIR" \
          --trunk-size "$SERVER_WARMUP_TRUNK_SIZE" \
          --concurrency 1 \
          --total-samples 1 \
          --stagger-ms 0 \
          --sil-offset 0 \
          --question-offset 0 \
          --temperature 1.0 \
          --voice "$VOICE_TYPE_VALUE" \
          --prefix-max-tokens 2 \
          --max-tokens "$SERVER_WARMUP_MAX_TOKENS" \
          "${warmup_media_args[@]}" \
          "${warmup_text_args[@]}" \
          > "$WARMUP_DIR.log"
        echo "server_warmup_done=$WARMUP_DIR"
        ;;
      0|false|FALSE|no|NO)
        echo "server_warmup=disabled"
        ;;
      *)
        echo "SGLANG_OMNI_SERVER_WARMUP must be 1/0, true/false, or yes/no; got: $SERVER_WARMUP" >&2
        exit 1
        ;;
    esac
    exit 0
  fi
  if ! kill -0 "$(cat "$RUN_DIR/server.pid")" 2>/dev/null; then
    echo "Stable server exited during startup" >&2
    tail -n 160 "$RUN_DIR/server.log" >&2
    exit 1
  fi
  if [ $((i % 30)) -eq 0 ]; then
    echo "waiting ${i}s"
    tail -n 12 "$RUN_DIR/server.log" || true
  fi
  sleep 1
done

echo "Stable server did not become ready within timeout" >&2
tail -n 200 "$RUN_DIR/server.log" >&2
exit 1
